import type { Metadata } from "next";
import { Play} from 'next/font/google'
import "./styles/globals.css";
import Footer from "./components/footer";
import Header from "./components/header";

const play = Play({ subsets: ['latin'], weight: ['400', '700'], display: 'swap' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${play.className} antialiased bg-background overflow-x-hidden`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
